module.exports={
    MONGOURI: process.env.MONGOURI,
    JWT_SECRET: process.env.JWT_SECRET,
    WATSON_ASSISTANT_APIKEY: process.env.WATSON_ASSISTANT_APIKEY,
    WATSON_ASSISTANT_URL: process.env.WATSON_ASSISTANT_URL,
    WATSON_ASSISTANT_ID: process.env.WATSON_ASSISTANT_ID,
    SENDGRID_ID: process.env.SENDGRID_ID 
}